### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ImranDoet** [ImranDoet/CorpusculumLib#1]
- [ ] NPCs must experience physics (gravity, block collision, moving up and down slabs/stairs when moving, this also includes proper collision with non-full blocks like snow, enchantment table, etc.) Base Citizens functionality (automatic)
- [ ] NPCs must be able to fly with the Elytra This can be simulated with some Bukkit Entity setVelocity calls, and I think they might just glide normally by default (ie you only need velocity adjustments to keep them on course, you don't necessarily have to simulate the flight mechanics)
- [ ] NPCs must be able to ride boats, horses, pigs, minecarts Base Citizens functionality (MountTrait), or Bukkit (passenger related calls on Entity)
- [ ] NPCs must not be visible in the tablist Base Citizens functionality (automatic) other than previously mentioned imperfections (flashing glitch) which is unavoidable to the best of our knowledge, but doesn't have too much impact other than looking funny if you spot it
- [ ] NPCs must be able to be hit with projectiles (snowballs, arrows, etc.) Base Citizens functionality and fire a custom event easily added, internally or externally (listen to the base EntityDamage event and check if the damaged entity is an NPC)
- [ ] NPCs must trigger pressure plates when standing on them I believe this is in base Citizens and automatic, not 100% positive - if it's not that can be added internally on request
- [ ] NPCs must be able to shoot a bow, throw snowballs, eggs, etc. This can be done in Bukkit - Sentinel does this as part of basic operation, use Sentinel or just reference the Sentinel source code (on GitHub)
- [ ] showToPlayer(Player) Bukkit for player-type NPCs, Denizen for all else
- [ ] hideFromPlayer(Player) Bukkit for player-type NPCs, Denizen for all else (NMSHandler.getInstance().getEntityHelper().hideEntity(Player, Entity, false);)
- [ ] Set<Player> getPlayersVisibleTo() you can easily just track this yourself if you're controlling it, though there's call to read it at least in Denizen
- [ ] setDisplayName(String) + Getter Base Citizens functionality
- [ ] setSkin(?) Base Citizens functionality (SkinnableEntity class, or "/npc skin" command)
- [ ] teleport(Location) Base Citizens functionality, or Bukkit
- [ ] Location getLocation() Base Citizens functionality, or Bukkit
- [ ] setVelocity(Vector) + Getter Bukkit
- [ ] setItemInHand() + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setItemInOffHand() + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setBoots(ItemStack) + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setLeggings(ItemStack) + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setChestPlate(ItemStack) + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setHelmet(ItemStack) + Getter Base Citizens functionality (Equipment trait), or Bukkit
- [ ] setOnFire(boolean) + Getter Bukkit (entity#setFireTicks)
- [ ] setCrouched(boolean) + Getter Bukkit (player#setSneaking) (also ref SneakingTrait in Denizen)
- [ ] setSprinting(boolean) + Getter Bukkit (player#setSprinting)
- [ ] setEating(boolean) + Getter Base Citizens functionality (PlayerAnimation.EAT_FOOD)
- [ ] setDrinking(boolean) + Getter Base Citizens functionality (same as eating)
- [ ] setBlocking(boolean) + Getter Base Citizens functionality (PlayerAnimation.START_USE_OFFHAND_ITEM or START_USE_MAINHAND_ITEM ... there is an open issue for this not properly persisting longer than half a second)
- [ ] setGlowing(boolean) + Getter Bukkit
- [ ] setNumberOfArrowsInBody(int) + Getter Denizen (NMSHandler.getInstance().getEntityHelper().setBodyArrows(Entity, numArrows);)
- [ ] swingArm() Base Citizens functionality (PlayerAnimation.ARM_SWING)
- [ ] swinOffhandArm() I don't think this exists as a concept within minecraft? I might be wrong.
- [ ] jump() Bukkit (just ent.setVelocity(ent.getVelocity().add(0, 1, 0)) tbh)
- [ ] showDamage() (npc turns red as if it has experienced damage) Base Citizens functionality (PlayerAnimation.HURT)
